import React, { useState } from 'react';
import { SearchState, AppState } from './types';
import { analyzeTicker } from './services/geminiService';
import Dashboard from './components/Dashboard';
import ReportView from './components/ReportView';
import LoadingState from './components/LoadingState';

const App: React.FC = () => {
  const [state, setState] = useState<SearchState>({
    query: '',
    status: AppState.IDLE,
  });

  const handleSearch = async (ticker: string, startYear: number, endYear: number) => {
    setState({ query: ticker, status: AppState.LOADING });
    try {
      const data = await analyzeTicker(ticker, startYear, endYear);
      setState({ 
        query: ticker, 
        status: AppState.SUCCESS, 
        data 
      });
    } catch (err: any) {
      console.error(err);
      setState({ 
        query: ticker, 
        status: AppState.ERROR, 
        error: err.message || "Failed to analyze ticker. Please try again."
      });
    }
  };

  const handleBack = () => {
    setState(prev => ({ ...prev, status: AppState.IDLE, error: undefined }));
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 selection:bg-blue-200">
      {/* Navbar */}
      <nav className="border-b border-slate-200 bg-white/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center cursor-pointer" onClick={handleBack}>
              <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-cyan-500 rounded-lg flex items-center justify-center font-bold text-white mr-2 shadow-sm">
                F
              </div>
              <span className="font-bold text-xl tracking-tight text-slate-900">Firm Analysis Assistant</span>
            </div>
            <div className="text-sm text-slate-500 hidden sm:block">
              Research Agent v1.0
            </div>
          </div>
        </div>
      </nav>

      <main className="container mx-auto px-4 py-8">
        {state.status === AppState.IDLE && (
          <Dashboard onSearch={handleSearch} status={state.status} />
        )}

        {state.status === AppState.ERROR && (
          <Dashboard onSearch={handleSearch} status={state.status} error={state.error} />
        )}

        {state.status === AppState.LOADING && (
          <LoadingState />
        )}

        {state.status === AppState.SUCCESS && state.data && (
          <ReportView data={state.data} onBack={handleBack} />
        )}
      </main>
      
      {/* Footer */}
      <footer className="border-t border-slate-200 mt-auto py-8 text-center text-slate-500 text-sm">
        <p>Disclaimer: Not financial advice. Data generated by AI and may be inaccurate.</p>
      </footer>
    </div>
  );
};

export default App;